// Achievements. check(S) returns true when earned. S is the game state.
const A = (id, name, desc, check, icon = '★', secret = false) => ({ id, name, desc, check, icon, secret });

export const ACHIEVEMENTS = [
  // Grabbing
  A('first', 'Hands On', 'Pick up your first plush.', (S) => S.stats.plush >= 1, '🧸'),
  A('p10', 'Warm Up', 'Pick up 10 plush.', (S) => S.stats.plush >= 10),
  A('p100', 'Getting a Feel', 'Pick up 100 plush.', (S) => S.stats.plush >= 100),
  A('p1k', 'Sorter', 'Pick up 1,000 plush.', (S) => S.stats.plush >= 1000),
  A('p10k', 'Shift Supervisor', 'Pick up 10,000 plush.', (S) => S.stats.plush >= 10000),
  A('p100k', 'Rot Baron', 'Pick up 100,000 plush.', (S) => S.stats.plush >= 100000),
  A('p1m', 'One in a Million', 'Process 1,000,000 plush.', (S) => S.stats.plush >= 1000000, '💎'),
  // Selling
  A('sell1', 'First Sale', 'Sell a plush at the bin.', (S) => S.stats.sold >= 1, '💰'),
  A('swish', 'Swish!', 'Throw a plush into the bin from 8m away.', (S) => S.stats.bestSwish >= 8, '🏀'),
  A('swish2', 'Half Court', 'Throw a plush into the bin from 18m away.', (S) => S.stats.bestSwish >= 18, '🏀'),
  A('combo5', 'On a Roll', 'Reach a x5 sell streak.', (S) => S.stats.bestStreak >= 5, '🔥'),
  A('combo20', 'Unstoppable', 'Reach a x20 sell streak.', (S) => S.stats.bestStreak >= 20, '🔥'),
  A('earn1k', 'Pocket Change', 'Earn 1,000 Fluff in total.', (S) => S.totalEarned >= 1000, '🪙'),
  A('earn100k', 'Fluff Mogul', 'Earn 100,000 Fluff in total.', (S) => S.totalEarned >= 100000, '🪙'),
  A('earn10m', 'Plush Tycoon', 'Earn 10,000,000 Fluff in total.', (S) => S.totalEarned >= 10000000, '🪙'),
  // Rarity
  A('rare1', 'Something Different', 'Find a Rare plush.', (S) => S.stats.rar[2] >= 1, '🔷'),
  A('epic1', 'Purple Patch', 'Find an Epic plush.', (S) => S.stats.rar[3] >= 1, '🟣'),
  A('leg1', 'Golden Hour', 'Find a Legendary plush.', (S) => S.stats.rar[4] >= 1, '🟠'),
  A('myth1', 'Impossible', 'Find a Mythic plush.', (S) => S.stats.rar[5] >= 1, '🌸'),
  A('shiny1', 'Ooh, Shiny', 'Find a shiny plush.', (S) => S.stats.shiny >= 1, '✨'),
  A('shiny10', 'Magpie', 'Find 10 shiny plush.', (S) => S.stats.shiny >= 10, '✨'),
  // Plushdex
  A('dex25', 'Collector', 'Discover 50 species.', (S) => Object.keys(S.dex).length >= 50, '📖'),
  A('dex75', 'Curator', 'Discover 150 species.', (S) => Object.keys(S.dex).length >= 150, '📖'),
  A('dex300', 'Archivist', 'Discover 300 species.', (S) => Object.keys(S.dex).length >= 300, '📖'),
  A('dex450', 'Taxonomist', 'Discover 450 species.', (S) => Object.keys(S.dex).filter((k) => +k < 990).length >= 450, '📖'),
  A('dex700', 'Field Guide', 'Discover 700 species.', (S) => Object.keys(S.dex).filter((k) => +k < 990).length >= 700, '📖'),
  A('dex850', 'Naturalist', 'Discover 850 species.', (S) => Object.keys(S.dex).filter((k) => +k < 990).length >= 850, '📖'),
  A('dexall', 'Gotta Squish Em All', 'Discover all 960 species.', (S) => Object.keys(S.dex).filter((k) => +k < 990).length >= 960, '📚'),
  A('fake1', 'Fool\'s Gold', 'Pick up a counterfeit Rotto Supremo.', (S) => [990, 991, 992, 993].some((d) => S.dex[d]), '🪙'),
  A('fakeall', 'Connoisseur of Fakes', 'Find all four counterfeits.', (S) => [990, 991, 992, 993].every((d) => S.dex[d]), '🪙'),
  A('remains1', 'Last Shift', 'Find the gear of a lost worker.', (S) => (S.stats.remains || 0) >= 1, '⛑️'),
  A('remains10', 'Grave Digger', 'Find the gear of 10 lost workers.', (S) => (S.stats.remains || 0) >= 10, '⛑️'),
  A('remains40', 'Memorial', 'Find the gear of 40 lost workers.', (S) => (S.stats.remains || 0) >= 40, '⛑️'),
  A('km1', 'One Kilometer', 'Be 1 km from Sorting Bay 07.', (S) => (S.stats.maxDist || 0) >= 1000, '📏'),
  A('km2', 'Two Kilometers', 'Be 2 km from Sorting Bay 07.', (S) => (S.stats.maxDist || 0) >= 2000, '📏'),
  A('km3', 'Almost Daylight', 'Be 3 km from Sorting Bay 07.', (S) => (S.stats.maxDist || 0) >= 3000, '📏'),
  A('km4', 'No One Comes This Far', 'Be 4 km from Sorting Bay 07.', (S) => (S.stats.maxDist || 0) >= 4000, '📏', true),
  A('slide1', 'Rockslide', 'Start a slide by climbing.', (S) => (S.stats.slides || 0) >= 1, '🏔️'),
  A('belt1', 'Industrial Revolution', 'Build a conveyor belt.', (S) => (S.stats.built || 0) >= 1, '🛤️'),
  A('mech1', 'Robot Labor', 'Build a Mech Scooper.', (S) => S.entities.some((e) => e.type === 'mech'), '🤖'),
  A('bulk1', 'Wall It Off', 'Build a bulkhead.', (S) => (S.stats.bulk || 0) >= 1, '🪧'),
  // Mining
  A('dig10', 'Burrow', 'Dig 10 meters of tunnel in total.', (S) => S.stats.cells * 0.6 / 6 >= 10, '⛏️'),
  A('dig100', 'Mole Person', 'Dig 100 meters of tunnel in total.', (S) => S.stats.cells * 0.6 / 6 >= 100, '⛏️'),
  A('dig1k', 'Earth Mover', 'Dig 1 kilometer of tunnel in total.', (S) => S.stats.cells * 0.6 / 6 >= 1000, '⛏️'),
  A('prop1', 'Safety First', 'Place a support frame.', (S) => S.stats.props >= 1, '🪵'),
  A('prop25', 'Timberman', 'Place 25 support frames.', (S) => S.stats.props >= 25, '🪵'),
  A('prop100', 'Structural Engineer', 'Place 100 support frames.', (S) => S.stats.props >= 100, '🏗️'),
  A('creak', 'Did You Hear That?', 'Hear a roof creak.', (S) => S.stats.creaks >= 1, '😬'),
  A('collapse1', 'Cave-In', 'Witness a collapse.', (S) => S.stats.collapses >= 1, '💥'),
  A('collapse25', 'Occupational Hazard', 'Witness 25 collapses.', (S) => S.stats.collapses >= 25, '💥'),
  A('buried', 'Buried Alive', 'Get buried under plush.', (S) => S.stats.buried >= 1, '⚰️'),
  A('buried5', 'Frequent Digger', 'Get buried 5 times.', (S) => S.stats.buried >= 5, '⚰️'),
  A('deep30', 'Ten Stories Down', 'Reach 10m below the surface of the pile.', (S) => S.stats.maxDepth >= 10, '🕳️'),
  A('deep60', 'Mantle', 'Reach 20m below the surface of the pile.', (S) => S.stats.maxDepth >= 20, '🕳️'),
  // Upgrades & machines
  A('up1', 'Investment', 'Buy your first upgrade.', (S) => S.stats.upgrades >= 1, '🛒'),
  A('up10', 'Tooled Up', 'Buy 10 upgrade levels.', (S) => S.stats.upgrades >= 10, '🛒'),
  A('up40', 'Fully Operational', 'Buy 40 upgrade levels.', (S) => S.stats.upgrades >= 40, '🛒'),
  A('bag16', 'Pack Mule', 'Carry capacity of 16 or more.', (S) => (S.up.bag || 0) >= 4, '🎒'),
  A('rig1', 'Automation', 'Place a Claw Rig.', (S) => S.stats.rigs >= 1, '🦾'),
  A('rig8', 'Claw Farm', 'Run 8 Claw Rigs at the same time.', (S) => S.entities.filter((e) => e.type === 'claw').length >= 8, '🦾'),
  A('borer1', 'Boring, Technically', 'Launch a Tunnel Borer.', (S) => S.stats.borers >= 1, '🚇'),
  A('lantern', 'Let There Be Light', 'Hang a Work Lantern.', (S) => S.stats.lanterns >= 1, '🏮'),
  A('lens', 'See the Strain', 'Buy the Stress Lens.', (S) => (S.up.stress || 0) >= 1, '👁️'),
  // Time / misc
  A('hour', 'Overtime', 'Play for one hour.', (S) => S.stats.playSecs >= 3600, '⏱️'),
  A('walk1k', 'Steps', 'Walk 1,000 meters.', (S) => S.stats.walked >= 1000, '👟'),
  A('toss100', 'Pitcher', 'Throw 100 plush.', (S) => S.stats.thrown >= 100, '⚾'),
  A('climb', 'King of the Pile', 'Climb 15m above the floor.', (S) => S.stats.maxHeight >= 15, '⛰️'),
  A('noprop', 'Brave or Foolish', 'Dig 5 meters below the surface without a support frame.', (S) => S.stats.noPropDeep, '🙈', true),
  // Endings
  A('cart1', 'Rolling', 'Roll out a cart.', (S) => !!S.cart || (S.stats.cartUsed || 0) > 0, '🛒'),
  A('cache1', 'Spare Parts', 'Open a worker\'s supply cache.', (S) => (S.stats.caches || 0) >= 1, '📦'),
  A('cache10', 'Scavenger', 'Open 10 supply caches.', (S) => (S.stats.caches || 0) >= 10, '📦'),
  A('gear1', 'Dressed for Work', 'Craft a piece of gear.', (S) => Object.values(S.gear || {}).some((v) => v > 0), '🧰'),
  A('scav1', 'Loose Ends', 'Craft a Scavenger Magnet.', (S) => ((S.gear || {}).scavenge || 0) >= 1, '🧲'),
  A('gold1', 'Golden Hour', 'Sell during a Golden Hour.', (S) => (S.stats.goldenSales || 0) >= 1, '🌟'),
  A('boom1', 'Fuse Burns', 'Have a Razzo go off in your hands.', (S) => (S.stats.boom || 0) >= 1, '🧨'),
  A('surge1', 'Lights Out', 'Live through a grid surge.', (S) => (S.stats.surges || 0) >= 1, '⚡'),
  A('crew1', 'Hired Help', 'Own a Scrapper Bot.', (S) => (S.crew || []).length >= 1, '🤖'),
  A('crew5', 'Small Army', 'Own five Scrapper Bots.', (S) => (S.crew || []).length >= 5, '🤖'),
  A('botlv', 'Growing Up', 'Level a bot up ten times.', (S) => (S.stats.botLevels || 0) >= 10, '📈'),
  A('contract1', 'Fulfilled', 'Complete a contract.', (S) => (S.stats.contracts || 0) >= 1, '📋'),
  A('contract20', 'Reliable Supplier', 'Complete 20 contracts.', (S) => (S.stats.contracts || 0) >= 20, '📋'),
  A('slide200', 'Landslide', 'Set off 200 plush slipping in one game.', (S) => (S.stats.slides || 0) >= 200, '⛰️'),
  A('slide3k', 'Moved a Mountain', 'Set off 3,000 plush slipping.', (S) => (S.stats.slides || 0) >= 3000, '🏔️'),
  A('cartshot', 'Nice Shot', 'Throw a plush into your cart.', (S) => (S.stats.cartCatch || 0) >= 1, '🏀'),
  A('cartshot50', 'Three Pointer', 'Land 50 plush in your cart.', (S) => (S.stats.cartCatch || 0) >= 50, '🏀'),
  A('binmag', 'Magnetic', 'Buy the Bin Magnet.', (S) => (S.up.magnet || 0) >= 1, '🧲'),
  A('probe', 'Careful Climber', 'Buy the Slope Probe.', (S) => (S.up.slopeprobe || 0) >= 1, '📐'),
  A('jack1', 'Jacked Up', 'Buy Hydraulic Jacks.', (S) => (S.up.jacks || 0) >= 1, '🛠️'),
  A('scan100', 'Clean Sweep', 'Scan 100 plush through detector gates.', (S) => (S.stats.scans || 0) >= 100, '🚨'),
  A('scan2k', 'Customs', 'Scan 2,000 plush through detector gates.', (S) => (S.stats.scans || 0) >= 2000, '🛂'),
  A('botscan', 'Checked In', 'Have a robot scanned at a gate.', (S) => (S.stats.botScans || 0) >= 1, '🤖'),
  A('botscan50', 'Regular Traffic', 'Scan robots through a gate 50 times.', (S) => (S.stats.botScans || 0) >= 50, '🤖'),
  A('split1', 'Fork in the Belt', 'Build a Belt Splitter.', (S) => (S.stats.splitters || 0) >= 1, '🔱'),
  A('split10', 'Distribution Network', 'Build 10 Belt Splitters.', (S) => (S.stats.splitters || 0) >= 10, '🔱'),
  A('belts50', 'Conveyor Belt Fan', 'Build 50 belts, machines and gates.', (S) => (S.stats.built || 0) >= 50, '🛤️'),
  A('belts300', 'Factory Floor', 'Build 300 belts, machines and gates.', (S) => (S.stats.built || 0) >= 300, '🏭'),
  A('die5', 'Slow Learner', 'Die five times.', (S) => (S.stats.deaths || 0) >= 5, '💀'),
  A('medic', 'Patched Up', 'Use a medkit.', (S) => (S.stats.medkits || 0) >= 1, '🩹'),
  A('tank', 'Deep Breath', 'Buy the Emergency Air Tank.', (S) => (S.up.airtank || 0) >= 1, '🫧'),
  A('hardhat4', 'Thick Skull', 'Fully upgrade the Hard Hat.', (S) => (S.up.hpmax || 0) >= 4, '⛑️'),
  A('lumber', 'Lumberjack', 'Own 100 building material at once.', (S) => Object.values(S.mats || {}).reduce((a, b) => a + b, 0) >= 100, '🪵'),
  A('dyn1', 'Stick of Dynamite', 'Buy Dynamite.', (S) => (S.up.dynamite || 0) >= 1, '🧨'),
  A('throw6', 'Cannon Arm', 'Max out the Throwing Arm.', (S) => (S.up.throw || 0) >= 6, '⚾'),
  A('died', 'Back From the Pile', 'Die in the warehouse and wake up on the floor.', (S) => (S.stats.deaths || 0) >= 1, '💀'),
  A('passout', 'Dust Lungs', 'Pass out from dust.', (S) => (S.stats.passedOut || 0) >= 1, '😵'),
  A('blast1', 'Fire in the Hole', 'Set off a blasting charge.', (S) => (S.stats.blasts || 0) >= 1, '🧨'),
  A('blast20', 'Quarryman', 'Set off 20 charges.', (S) => (S.stats.blasts || 0) >= 20, '🧨'),
  A('theone', 'The One', 'Find Il Rotto Supremo.', (S) => S.ending === 'plush', '👑'),
  A('exit', 'Daylight', 'Dig your way out of the warehouse.', (S) => S.ending === 'exit', '🚪'),
  A('speed', 'Needle Speedrun', 'Find The One in under 30 minutes of play.', (S) => S.ending === 'plush' && S.stats.playSecs < 1800, '⚡', true),
];
