// Every control in the game, in one place. The pause menu's Controls tab and the How to Play screen are both drawn from this table,
// and a test checks it against the real key handlers, so the list cannot drift from what the keys actually do.
// keys: what is drawn on the key caps. codes: the KeyboardEvent codes the game handles for it ('Mouse0', 'Mouse2', 'Wheel' for the mouse).
export const CONTROLS = [
  { group: 'Moving', rows: [
    { keys: ['W', 'A', 'S', 'D'], codes: ['KeyW', 'KeyA', 'KeyS', 'KeyD'], what: 'Walk. Click the game once to capture the mouse, then the mouse looks around. On a ladder W (or Space) climbs and S goes down; keep pressing W at the top to step onto the plate.' },
    { keys: ['Shift'], codes: ['ShiftLeft'], what: 'Sprint (hold).' },
    { keys: ['Space'], codes: ['Space'], what: 'Jump. When you are trapped under plush, hold it to punch upward.' },
    { keys: ['C'], codes: ['KeyC'], what: 'Crouch (hold) to fit low tunnels. Ctrl is not used, because Ctrl+W closes the browser tab.' },
  ] },
  { group: 'Hands', rows: [
    { keys: ['Left click'], codes: ['Mouse0'], what: 'Grab the plush you look at. Hold to keep grabbing until your hands or cart are full. Click while holding plush to throw one. With a belt or a Vacuum Hose out, a click is the laying mode instead: the first click anchors a route (at the open end of a line if you aim at one), the preview shows the whole curved route to where you aim with its length and cost and turns gold when its end feeds a bin, and the next click lays all of it and carries on from its end. Right click or Q puts the route down.' },
    { keys: ['Z'], codes: ['KeyZ'], what: 'Throw one plush from your hands.' },
    { keys: ['Right click', 'R', 'P'], codes: ['Mouse2', 'KeyR', 'KeyP'], what: 'Punch: knock loose the plush in front of you, or punch yourself out of a hole. (R flips a ramp or a lift up and down, or turns a floor pad (the opening of a plate in a cube too), catwalk, wall, door or stair, or the heading of a jump pad, instead while you hold one, and picks the route shape while the Line Planner or a route is on. With a belt or hose in hand and no route, R turns the next piece a quarter turn; the mouse turns it back. Right click puts a route you are aiming down before it punches.)' },
    { keys: ['E'], codes: ['KeyE'], what: 'Use what you aim at: terminal, crafting bench, generators (any size: hand it plush to burn, or press E with empty hands to switch AUTO and RESERVE), power switches and breakers, hanging lanterns (on or off), sorters, vaults, depots, Smart and Programmable Splitters (their rules) and Priority Mergers (their lane order). On an earth mover it empties the hopper into your hands, or parks it and sends it back to work. Aim at a bot to select it, then E on a target to command it. Lockers, crates, silos, depots, signs and lamps open their own panel. On a detector arch it opens the target panel. On a Vehicle Scanner that holds The One it takes it out (the alarm stops, the trucks roll again). On a Portal (a giant arch at the mouth of the pile) it parks or starts the auto-driver; on a Haul Truck that ran out of battery it spends a Charge Pack. A door opens or closes (with no power it turns a slow hand crank), the call panel at a landing calls the elevator, and in its cab it goes where you look: up, down or level for the next stop (with no power it turns by hand, slowly, and it never runs through a cut or unshored shaft). On a placed Jump Pad it makes the angle 5 degrees steeper (crouch + E turns the heading). On the remains of a worker or a supply cache it opens them and the notes go in your Field Journal (L); bots and machines stop short of them and flag them (only a Bot Scholar carries the note of a worker home; caches always need you). On a care package crate dropped by the courier drone it opens the crate (walking into it does too); the compass marks it CARE, or GOLD for a gold one.' },
    { keys: ['Shift', 'E'], codes: ['KeyE'], what: 'Copy the settings of the machine you aim at (Sorting Boxes, Smart and Programmable Splitters and Priority Mergers now, more kinds as they arrive). Then E on another of the same kind pastes them. Shift+E at nothing drops the copy. Doors (lock and sensor) and Jump Pads (angle and heading) copy too.' },
    { keys: [';'], codes: ['Semicolon'], what: 'Bins: aim at a machine (truck, digger, borer, claw rig, mech, Portal, Rail Station or Cart), the last piece of a belt line, a bot or your cart, or have a bot selected, and press ; to pick the bin it sells at: Auto (what it always did), the SORT bin or a Depot Beacon. In the panel ; steps to the next bin, Rename names a beacon, and every bin shows its distance and what it sold today. With nothing aimed it lists every bin. A selected bot also takes E on a Depot Beacon.' },
    { keys: ['Shift', ';'], codes: ['Semicolon'], what: 'Copy the bin of what you aim at (or of the selected bot). E on another machine, belt end, cart or bot pastes it, whatever kind it is. Shift+; at nothing drops the copy. Shift+E copies all of a machine\'s settings, its bin included, for the same kind.' },
    { keys: ['F'], codes: ['KeyF', 'KeyO'], what: 'Flashlight on or off (O works too).' },
    { keys: ['K'], codes: ['KeyK'], what: 'Use a medkit.' },
    { keys: ['U'], codes: ['KeyU'], what: 'Roll your cart out, park it, or call it back to follow you. (X next to it stows it when it is empty.)' },
    { keys: ['`'], codes: ['Backquote'], what: 'Belt intake on or off (on by default once you own Conveyor Belts). While it is on, a plain belt close to you pulls plush off your hands, then off your cart (a parked cart too), up to 2 a second within 2 m, more with the Belt Intake upgrade (up to 256 a second within 6 m). It takes nothing while you hold a build item, never takes The One, and a full belt stops the pull. A bin that is closer than the belt still wins.' },
    { keys: ['H'], codes: ['KeyH'], what: 'Hold for 2.5 seconds: emergency recall to the nearest depot.' },
  ] },
  { group: 'Tools and building', rows: [
    { keys: ['1', '2', '...', '9'], codes: ['Digit1', 'Digit2', 'Digit3', 'Digit4', 'Digit5', 'Digit6', 'Digit7', 'Digit8', 'Digit9'], what: 'Take out the tool in that hotbar slot. Press the same number again to put it away. An empty slot is bare hands.' },
    { keys: ['[', ']', 'Wheel'], codes: ['BracketLeft', 'BracketRight', 'Wheel'], what: 'Step through your hotbar tools.' },
    { keys: ['Q'], codes: ['KeyQ'], what: 'Put your tool away / take it out again. With a Power Cable wire in your hand it drops the wire instead, and with a belt or hose route anchored it puts the route down first.' },
    { keys: ['Left click'], codes: ['Mouse0'], what: 'With a Power Cable out: click a generator, pole or machine to start a wire that follows your crosshair, click a second one to attach it (up to 14 m, more with Grid Range). The end under your crosshair glows gold or green, red when it is too far or full. Click empty air to cancel, click the same pair again to remove the cable. Power travels only through cables: wire a generator to a pole, then every machine to a pole or generator. Hanging lanterns may chain: pole to the first lantern, then that lantern to the next.' },
    { keys: ['Ctrl'], codes: ['ControlLeft'], what: 'While placing floor pads or plates: hold it to align to the world grid instead of snapping to the nearest piece. Do not hold it while pressing W: Ctrl+W closes the browser tab.' },
    { keys: ['B'], codes: ['KeyB'], what: 'Set down the building item in your hand. Hold B to lay a line of belts, Vacuum Hose pieces or haul road plates (sweep the mouse and the cells in between are laid too, so a curve stays one connected line; a hose is one hose with a single flared mouth at its open start, and one press up to 3 cells past the last hose piece lays the cells between too, as the aim shows), or set a higher mark belt over an old one to upgrade it. With a floor pad: hold B (or left click), drag along a line and let go to lay up to 10 pads in one go (hold Shift to drag a block up to 5 x 5). Aimed into a frame cube with Stacked Building, a floor pad is a floor or ceiling plate, two stairs (or two ramps) are a switchback stair, a ladder hangs on the rim of an opening and a wall is a door frame (hold Ctrl for the plain piece instead).' },
    { keys: ['.'], codes: ['Period'], what: 'Belt or hose in hand: Line Planner on or off. B sets the start, aim the end, B again lays the whole line (up to 64 tiles, bought at the bench price if you do not hold enough). Lift in hand: one cell taller.' },
    { keys: [','], codes: ['Comma'], what: 'Line Planner on: next route shape (R does it too, and the wheel once the start is set): horizontal first, vertical first, around and over, under. Lift in hand: one cell shorter.' },
    { keys: ['Left', 'Right'], codes: ['ArrowLeft', 'ArrowRight'], what: 'With a frame in hand: turn it freely so a tunnel can curve (hold Shift for fine turns). With anything else they step through the hotbar.' },
    { keys: ['Down'], codes: ['ArrowDown'], what: 'With a frame in hand: back to the grid, snapping to other frames again.' },
    { keys: ['X'], codes: ['KeyX'], what: 'Knock down what you aim at and get it back (the hammer in slot 1 does the same with a click). Shift+X takes down a whole zoop: every floor pad, catwalk or wall laid in the same go.' },
    { keys: ['-', '='], codes: ['Minus', 'Equal'], what: 'With Scoop Hands and nothing to build in hand: scoop 3 fewer (-) or 3 more (=) plush per grab, from 0 (just the one plush you aim at) up to the most your hands allow, starting at 3 (the SCOOP dial shows it and has its own minus and plus buttons you can click or tap, also with a pad in hand; turn it down to dig a tunnel without bringing the roof down). Alt with these keys is the VACUUM dial instead. With a floor pad, catwalk or wall in hand: shorten or lengthen the zoop, up to 10 in a line (with Shift on a pad: the width, up to 5 x 5). With a floor pad aimed into a frame cube (Stacked Building): pick the opening of the plate, full, landing or shaft. With a Leveling Pad: its size, 1 to 3 pads on a side. With a Jump Pad: its launch angle, 0 to 90 degrees in 5 degree steps.' },
    { keys: ['Alt', '-', '='], codes: ['Minus', 'Equal'], what: 'With the Plush Vacuum: Alt and - pull gentler, Alt and = pull harder, 10 percent of its full suction at a time (the VACUUM dial shows plush a second out of the most you own, and has its own minus and plus buttons, also with a pad in hand). It starts at 30 percent, never under 1 plush a second, and a lower setting also narrows the cone and takes only the layer you point at (it goes deeper as you keep pointing), so a tunnel roof is not pulled down. At 0 the vacuum is off and a click is a plain grab. Each player keeps their own setting.' },
    { keys: ['Shift', 'R'], codes: ['KeyR'], what: 'With a floor pad, catwalk or wall in hand: nudge the spot one cell off the grid (it cycles 0 to 3). Hold Ctrl instead to lock a pad to the world grid.' },
    { keys: ['Backspace'], codes: ['Backspace'], what: 'Mine Rail: in a cart, rush home (or back to the face when you are already at the base). On foot beside a cart, climb in and go; on foot anywhere near the track, call the nearest cart. A cart on a powered line runs 8 m/s, an unpowered one 2 m/s.' },
    { keys: ['E', 'Space'], codes: ['KeyE', 'Space'], what: 'On a Rail Cart: E loads the plush in your hands into it, or sits you in it when your hands are empty. In the cart, E or Space hops off. E on a Rail Station switches it between BASE and FACE.' },
    { keys: ['I'], codes: ['KeyI'], what: 'Inventory. In it: arrows move, 1-9 put the selected item on that hotbar slot, X clears a slot.' },
  ] },
  { group: 'Crew', rows: [
    { keys: ['V'], codes: ['KeyV'], what: 'The crew panel: every bot, its battery and what it is doing. It also has the Keep machines fueled switch for the whole crew and a Fuel duty switch on each bot: bots top up generators and Charging Stations, and dig fuel for one that runs low.' },
    { keys: ['T'], codes: ['KeyT'], what: 'Send the whole crew digging the way you face.' },
    { keys: ['Y'], codes: ['KeyY'], what: 'Call the whole crew home to unload.' },
    { keys: ['Esc'], codes: ['Escape'], what: 'With a bot selected: let it go (otherwise Esc opens this menu). It also cancels a power cable wire you are pulling.' },
  ] },
  { group: 'Screens', rows: [
    { keys: ['Tab'], codes: ['Tab'], what: 'Upgrade terminal (works anywhere).' },
    { keys: ['N'], codes: ['KeyN'], what: 'Plushdex: every species you have found.' },
    { keys: ['L'], codes: ['KeyL'], what: 'Field journal: your finds, and the Notes tab (every note read, with the clues about The One pieced together).' },
    { keys: ['J'], codes: ['KeyJ'], what: 'Achievements.' },
    { keys: ['Esc'], codes: ['Escape'], what: 'Pause menu.' },
    { keys: ['Enter'], codes: ['Enter'], what: 'Chat (only while you are playing together).' },
    { keys: ['F3'], codes: ['F3'], what: 'Show or hide the frame rate.' },
    { keys: ['M'], codes: ['KeyM'], what: 'Load meter: a small readout of supply, demand, storage and the last minute for the power grid you stand nearest to. Aim at a Load Meter, switch, breaker or battery for the same numbers.' },
  ] },
];
export const CONTROL_CODES = new Set(CONTROLS.flatMap((g) => g.rows.flatMap((r) => r.codes)));

// Keys no handler uses yet, held back for the Satisfactory waves so two agents never pick the same one. A wave moves its key into CONTROLS
// (with a row) and out of this table in the same change; a test checks that nothing here is handled by onKey and nothing is claimed twice.
export const RESERVED_KEYS = {
  F4: 'Wave 8: blueprint menu',
};
